begin
  require 'jeweler'

  Jeweler::Tasks.new do |gem|
    gem.name        = '<%= gem_name %>'
    gem.summary     = "SUMMARY"
    gem.description = gem.summary
    gem.authors     = ["NAME"]
    gem.email       = %q{EMAIL}
    gem.homepage    = 'http://github.com/USERNAME/<%= gem_name %>'

    gem.add_dependency 'dm-core', '~> <%= DMGen::DM_VERSION %>'

    gem.add_development_dependency 'rspec', '~> 1.3'
    gem.add_development_dependency 'yard', '~> 0.5'
  end

  Jeweler::GemcutterTasks.new

  FileList['tasks/**/*.rake'].each { |task| import task }
rescue LoadError
  puts 'Jeweler (or a dependency) not available. Install it with: gem install jeweler'
end
